# Generated by Django 5.0.3 on 2024-04-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_order_paid_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="image",
            field=models.ImageField(
                default=None, max_length=250, null=True, upload_to="images/order_image"
            ),
        ),
    ]
