# Generated by Django 5.0.3 on 2024-04-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_review_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
