# Generated by Django 5.0.3 on 2024-04-22 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_review_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="product",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
    ]
